introduction/urls.py
from django.urls import path
from . import views

app_name='introduction'
urlpatterns = [
    path('', views.main, name="main"),
    path('nikeXsacai/', views.sacai, name="sacai"),
    path('nikeXsupreme/', views.supreme, name="supreme"),
    path('nikeXstussy/', views.stussy, name="stussy"),
]

lifestyle/urls.py
from django.urls import path
from . import views

app_name='lifestyle'
urlpatterns = [
    path('', views.main2, name="main2"),
    path('daybreak/', views.daybreak, name="daybreak"),
    path('blazer/', views.blazer, name="blazer"),
]

posts/urls.py
from django.urls import path
from .views import *
app_name = "posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>', show, name="show"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:post_id>/create_comment', create_comment, name="create_comment"),
    path('<int:comment_id>/edit_comment', update_comment, name="update_comment"),
    path('<int:comment_id>/delete_comment', delete_comment, name="delete_comment"),
    path('<int:post_id>/post_like', post_like, name="post_like"),
    path('like_list/', like_list, name="like_list"),
]

project2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('introduction.urls')),
    path('lifestyle/', include('lifestyle.urls')),
    path('sports/', include('sports.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sports/urls.py
from django.urls import path
from . import views

app_name='sports'
urlpatterns = [
    path('', views.main3, name="main3"),
    path('airmax/', views.airmax, name="airmax"),
    path('jordan/', views.jordan, name="jordan"),
]

lifestyle/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model) :
    title = models.CharField(max_length= 50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to = 'images/', null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='like_user_set', through='Like')

    @property
    def like_count(self):
            return self.like_user_set.count()

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
            unique_together = (('user','post'))

sports/models.py
from django.db import models

# Create your models here.

introduction/views.py
from django.shortcuts import render

# Create your views here.
def main(request) :
    return render(request, 'introduction/main.html')
def sacai(request) :
    return render(request, 'introduction/sacai.html')
def supreme(request) :
    return render(request, 'introduction/supreme.html')
def stussy(request) :
    return render(request, 'introduction/stussy.html')   

lifestyle/views.py
from django.shortcuts import render

# Create your views here.
def main2(request) :
    return render(request, 'lifestyle/main2.html')
def daybreak(request) :
    return render(request, 'lifestyle/daybreak.html')
def blazer(request) :
    return render(request, 'lifestyle/blazer.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
# Create your views here.
def new(request):
    return render(request, 'posts/new.html')

def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        user = request.user
        Post.objects.create(title=title, content=content, image=image)
        return redirect('posts:main')

def main(request):
    posts = Post.objects.all()
    return render(request, 'posts/main.html', {'posts' : posts})
    
def show(request, id):
    post = Post.objects.get(pk=id)
    post.view_count += 1
    post.save()
    all_comments = post.comments.all()
    return render(request, 'posts/show.html', {'post' : post, 'comments' : all_comments })

def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method =='POST':
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image')
        post.save()
        return redirect('posts:show', post.id)
    return render(request, 'posts/update.html', {"post":post})

def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect("posts:main")

def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment.objects.create(content=comment_content, writer=current_user, post=post)
    return redirect('posts:show', post_id)

def update_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        post_id = comment.post.id 
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('posts:show', post_id)
    return render(request, 'posts/edit_comment.html', {'comment': comment})

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post_id = comment.post.id
    comment.delete()
    return redirect('posts:show', post_id)


@login_required
def post_like(request, post_id):
        post = get_object_or_404(Post, pk=post_id)

        if request.user in post.like_user_set.all():
                post.like_user_set.remove(request.user)
        else:
                post.like_user_set.add(request.user)
        if request.GET.get('redirect_to') == 'show':
                return redirect('posts:show', post_id)
        else:
                return redirect('posts:main')

@login_required
def like_list(request):
        likes = request.user.like_set.all()
        return render(request,'posts/like_list.html', {'likes':likes})

sports/views.py
from django.shortcuts import render

# Create your views here.
def main3(request) :
    return render(request, 'sports/main3.html')
def airmax(request) :
    return render(request, 'sports/airmax.html')
def jordan(request) :
    return render(request, 'sports/jordan.html')

introduction/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    
    <title>Nike Shoes</title>
  </head>
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/"><img src="https://i.ytimg.com/vi/NFUp71WyT-k/maxresdefault.jpg" width="70" height="40"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'posts:like_list'%}">Like <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'lifestyle:main2'%}">Lifestyle</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sports:main3'%}">Sports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:new' %}">Write</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">list</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
          <div class="dropdown-menu">
            {% if user.is_authenticated %} {# 유저가 로그인 중이면 #}
              <a class="dropdown-item" href="{% url 'account_logout' %}" class="nav-link">Logout</a>
              <a class="dropdown-item" href="{% url 'account_change_password' %}">Change PW</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'account_login' %}" class="nav-link">Login</a>
              <a class="dropdown-item" href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </nav>
{% block content %}
{% endblock %}
  <body>
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

introduction/templates/introduction/main.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Nike shoes</h1>
      <p class="lead">This page introduces Nike shoes. I hope you enjoy watching! </p>
    </div>
  </div>
  <div class="card-deck">
    <div class="card">
        <img src="https://www.stadiumgoods.com/media/catalog/product/b/v/bv0073_400_1_1.png" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">NikeXSacai</h5>
          <p class="card-text">In collaboration with Japanese high-fashion label sacai, designer Chitose Abe fused two iconic Nike shoes for a hybrid, double-themed design.</p>
          <a href="/nikeXsacai" class="btn btn-primary">Detail</a>
        </div>
    </div>
    <div class="card">
        <img src="https://m.threestep.co.kr/web/product/big/20200314/3a6fae59aed61d64d29281289091bb1d.jpg" class="card-img-top" >
        <div class="card-body">
          <h5 class="card-title">NikeXSupreme</h5>
          <p class="card-text">Supreme has just given an official release date for its upcoming Nike Air Force 1 Low collaboration. Although many have commented on the collab being too minimal, the small placement of the iconic Box Logo is just the right amount of flair to distinguish the collaboration, and maintain its classic New York appeal.</p>
          <a href="/nikeXsupreme" class="btn btn-primary">Detail</a>
        </div>
    </div>
    <div class="card">
      <img src="https://cdn.eyesmag.com/content/uploads/sliderImages/2020/03/31/stussy-nike-korea-release-info-01-e4f3ed67-9c07-4b7e-8952-ac41dc261f3e.jpg" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">NikeXStussy</h5>
        <p class="card-text">The Stussy x Nike Air Zoom Spiridon Cage 2 Fossil is one of two colourways of the retro running silhouette that’s set to launch as part of Nike’s latest collaboration with legendary Californian streetwear label Stussy.</p>
        <a href="/nikeXstussy" class="btn btn-primary">Detail</a>
      </div>
    </div>
  </div>
{% endblock %}

introduction/templates/introduction/sacai.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">NikeXSacai</h1>
      <p class="lead">Welcome to NikeXSacai World!</p>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3">
    <div class="col mb-6">
      <div class="card">
        <img src="https://lh3.googleusercontent.com/proxy/jT_3g_YMnPHnsgTreFbQGNHeswO9HXEYYe48tAwmA62MWtazBLsGpInNNOGBvjf9cFK_va-AvF8pXWAXQXMkRe4q7zVh3ekdnRdKSjBFPEeqqDX7oPUVN1xZ5KH7heENyi7zqNaWQMFVhH-ONd6Ei9lE4oY" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">NIKE X SACAI LDVWAFFLE BV0073-300</h5>
          <p class="card-text">Color : Green Gusto/Safety Orange/Black<br></br>
        Price : 179,000<br></br>
        Resell Price : 800,000 ~ 900,000</p>
        </div>
      </div>
    </div>
    <div class="col mb-6">
      <div class="card">
        <img src="https://pbs.twimg.com/media/D0nY92kVYAA7wU6.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">NIKE X SACAI LDVWAFFLE BV0073-400</h5>
          <p class="card-text">Color : Varsity Blue/Del Sol/Varsity Red/Black<br></br>
            Price : 179,000<br></br>
            Resell Price : 800,000 ~ 900,000</p>
        </div>
      </div>
    </div>
    <div class="col mb-6">
      <div class="card">
        <img src="https://media.endclothing.com/end-features/prodfeatures/36ef89ecefb6886a501d6bf193b911bf7d1a4c1f_bv0073-301_launches_hero_landscape_1.jpg?auto=compress,format" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">NIKE X SACAI LDVWAFFLE BV0073-301</h5>
          <p class="card-text">Color : Pine Green/Clay Orange/Pink<br></br>
            Price : 179,000<br></br>
            Resell Price : 600,000 ~ 700,000</p>
        </div>
      </div>
    </div>
    <div class="col mb-6">
      <div class="card">
        <img src="https://media.endclothing.com/end-features/prodfeatures/44423c5654650669253593a2efb6760c9aca395a_bv0073-100_launches_hero_landscape_1.jpg?auto=compress,format" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">NIKE X SACAI LDVWAFFLE BV0073-100</h5>
          <p class="card-text">Color : Summit White/Wolf Grey<br></br>
            Price : 179,000<br></br>
            Resell Price : 900,000 ~ 1,000,000</p>
        </div>
      </div>
    </div>
    <div class="col mb-6">
        <div class="card">
          <img src="https://media.endclothing.com/end-features/prodfeatures/5952bed019d46df4f61d2cf442c202b2dad8e887_bv0073-001_launches_hero_landscape_1.jpg?auto=compress,format" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">NIKE X SACAI LDVWAFFLE BV0073-001</h5>
            <p class="card-text">Color : Black/White/Gunsmoke<br></br>
                Price : 179,000<br></br>
                Resell Price : 800,000 ~ 900,000</p>
          </div>
        </div>
      </div>
      <div class="col mb-6">
        <div class="card">
          <img src="https://imseoulman.com/web/product/big/201906/dcd046f4b3db23f5a43615072ad1dc7d.jpg" class="card-img-top" >
          <div class="card-body">
            <h5 class="card-title">NIKE X SACAI BLAZER BLUE BV0072-001</h5>
            <p class="card-text">Color : Blue<br></br>
              Price : 168,000<br></br>
              Resell Price : 580,000 ~ 700,000</p>
          </div>
        </div>
      </div>
  </div>
{% endblock %}

introduction/templates/introduction/stussy.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">NikeXStussy</h1>
      <p class="lead">Welcome to NikeXStussy World!</p>
    </div>
  </div>
  <div class="card-deck">
    <div class="card">
        <img src="https://image-cdn.hypb.st/https%3A%2F%2Fkr.hypebeast.com%2Ffiles%2F2020%2F03%2Fstussy-nike-collavorative-air-zoom-spiridon-caged-2-collection-korea-release_0021_01-02.jpg?q=90&w=1400&cbr=1&fit=max" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Nike Air Zoom Spiridon Cage 2 Stussy Pure Platinum / CU1854-001</h5>
          <p class="card-text">Color : Pure Platinum/Black-White<br></br>
            Price : $160<br></br>
            Resell Price : 300,000 ~ 500,000</p>
        </div>
    </div>
    <div class="card">
        <img src="https://image-cdn.hypb.st/https%3A%2F%2Fkr.hypebeast.com%2Ffiles%2F2020%2F03%2Fstussy-nike-collavorative-air-zoom-spiridon-caged-2-collection-korea-release-ft-1.jpg?q=90&w=1400&cbr=1&fit=max" class="card-img-top" >
        <div class="card-body">
          <h5 class="card-title">Nike Air Zoom Spiridon Cage 2 Stussy Fossil / CQ5486-200</h5>
          <p class="card-text">Color : Fossil/Black-Fossil<br></br>
            Price : $160<br></br>
            Resell Price : 700,000 ~ 950,000</p>
        </div>
    </div>
    <div class="card">
      <img src="https://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory2&fname=http%3A%2F%2Fcfile21.uf.tistory.com%2Fimage%2F998107505EA6F01E32D610" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">Nike Air Zoom Spiridon Cage 2 Stussy Black / CQ5486-001</h5>
        <p class="card-text">Color : Black/Cool Grey-Black<br></br>
          Price : $160<br></br>
          Resell Price : 35,000 ~ 550,000</p>
      </div>
    </div>
  </div>
{% endblock %}

introduction/templates/introduction/supreme.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">NikeXSupreme</h1>
      <p class="lead">Welcome to NikeXSupreme World!</p>
    </div>
  </div>
  <div class="card-deck">
    <div class="card">
        <img src="https://www.street.co.kr/wp-content/uploads/2020/03/1-3.jpg" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">NIKE X SUPREME AIR FORCE 1 LOW / CU9225-100</h5>
          <p class="card-text">Color : White/White<br></br>
            Price : $95<br></br>
            Resell Price : 450,000 ~ 600,000</p>
          
        </div>
    </div>
    <div class="card">
        <img src="https://www.street.co.kr/wp-content/uploads/2020/03/5-2.jpg" class="card-img-top" >
        <div class="card-body">
          <h5 class="card-title">NIKE X SUPREME AIR FORCE 1 LOW / CU9225-001</h5>
          <p class="card-text">Color : Black/Black<br></br>
            Price : $95<br></br>
            Resell Price : 350,000 ~ 500,000</p>
          
        </div>
    </div>
  </div>
{% endblock %}

lifestyle/templates/lifestyle/blazer.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Nike original shoes : LifeStyle</h1>
      <p class="lead"> Nike's lifestyle shoes is loved all over the world. Because their fantastic design and good quility! </p>
    </div>
  </div>
{% endblock %}

lifestyle/templates/lifestyle/daybreak.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Nike original shoes : LifeStyle</h1>
      <p class="lead"> Nike's lifestyle shoes is loved all over the world. Because their fantastic design and good quility! </p>
    </div>
  </div>
{% endblock %}

lifestyle/templates/lifestyle/main2.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Nike original shoes : LifeStyle</h1>
      <p class="lead"> Nike's lifestyle shoes is loved all over the world. Because their fantastic design and good quility! </p>
    </div>
</div>
  <div class="card-deck">
    <div class="card">
        <img src="https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/c358caa2-ac12-42bb-8641-302e63b704f9/daybreak-shoe-Hxrl0S.jpg" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">Nike Daybreak</h5>
          <p class="card-text">The Nike Daybreak SP marks the return of the 1979 original, featuring suede and nylon on the upper and old-school graphics on the tongue for a '70s runner-inspired look and feel.</p>
            <a href="#" class="btn btn-primary">Detail</a>
        </div>
    </div>
    <div class="card">
        <img src="https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/qzfu1gccdxqeujgnhoda/blazer-mid-77-vintage-shoe-pMfjs8.jpg" class="card-img-top" >
        <div class="card-body">
          <h5 class="card-title">Nike Blazer</h5>
          <p class="card-text">The Nike Blazer Mid '77 Vintage harnesses the old-school look of Nike Basketball with a vintage midsole finish, making it look like you've been saving them for years.</p>
            <a href="#" class="btn btn-primary">Detail</a>
        </div>
    </div>
  </div>
{% endblock %}

posts/templates/posts/edit_comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mb-5">
    <h3>리뷰 수정하기</h3>
    <div class="container mt-5">
        <form class="form-row" action="{% url 'posts:update_comment' comment.id %}" method="POST">
        {% csrf_token %}
        <textarea class="form-control col-9 mr-2" name="content" placeholder="리뷰 내용 입력..." required>{{ comment.content }}</textarea>
        <input type="submit" class="btn btn-primary" value="확인">
        </form>
    </div>
</div>
{% endblock %} 

posts/templates/posts/new.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
        Write here!
    </h1>
    <form action="{% url 'posts:create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label>Content</label>
            <textarea class="form-control" name="content"></textarea>
        </div>
        <input type="submit" value="Complete" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 mb-5">
<h1>상세보기 페이지</h1><br>
<h3>글 제목 : {{ post.title }} </h3><br>
{% if post.user %}
    {% if post.user.username == 'user' %}
        <h3>작성자 : {{ post.user.last_name }}{{ post.user.first_name }}</h3><br>
    {% else %}
        <h3>작성자 : {{ post.user }}</h3><br>
    {% endif %}
{% else %}
        <h3>작성자 : 알 수 없음</h3><br>
{% endif %}
<h3>글 내용 : {{ post.content }} </h3><br>
<h3>작성 시각 : {{ post.created_at }} </h3><br>
<h3>조회수 : {{ post.view_count }}</h3>
<p>
    <a href="{% url 'posts:post_like' post.id%}?redirect_to=show">
        {% if user in post.like_user_set.all%}
            <i class="fas fa-heart"></i>
        {% else %}
            <i class="far fa-heart"></i>
        {% endif %}
    </a>
    {{ like.user }}
</p>
{% if post.image %}
    <img src = "{{post.image.url}}" width=500px><br>
{% endif %}
{% if user == post.user %}
<a href ="{% url 'posts:update' post.pk %}" class="btn btn-outline-primary">수정하기</a>
<a href ="{% url 'posts:delete' post.pk %}" class="btn btn-outline-danger">삭제하기</a>
{% endif %}

<div class="container mt-5">
    <form class="form-row" action="{% url 'posts:create_comment' post.id %}" method="POST">
      {% csrf_token %}
      <textarea class="form-control col-11 mr-2" name="content" placeholder="댓글 내용 입력..."></textarea>
      <input type="submit" class="btn btn-primary" value="확인">
    </form>
</div>
</div>
<div class="container mt-5 mb-5">
    {% for comment in comments %}
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <b>
                            {% if "user" in comment.writer.username %}
                                {{ comment.writer.last_name }}{{ comment.writer.first_name }}
                            {% else %}
                                {{ comment.writer }}
                            {% endif %}
                        </b> {{ comment.content }}
                    </div>
                    {% if user == comment.writer %}
                        <div class="col text-right">
                            <a href="{% url 'posts:update_comment' comment.id %}">수정</a>
                            <a href="{% url 'posts:delete_comment' comment.id %}">삭제</a>
                        </div>
                    {% endif %}
                </div>
                <small>{{ comment.created_at }}</small>
            </div>
            
        </div>
    {% endfor %}
</div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
        Revise
    </h1>
    <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label>Content</label>
            <textarea class="form-control" name="content"></textarea>
            <input type="file" name="image">
        </div>
        <input type="submit" value="Complete" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

sports/templates/sports/airmax.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Nike original shoes : LifeStyle</h1>
      <p class="lead"> Nike's lifestyle shoes is loved all over the world. Because their fantastic design and good quility! </p>
    </div>
  </div>
{% endblock %}

sports/templates/sports/jordan.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Nike original shoes : LifeStyle</h1>
      <p class="lead"> Nike's lifestyle shoes is loved all over the world. Because their fantastic design and good quility! </p>
    </div>
  </div>
{% endblock %}